(load (pathname "meninlabfiles/macroses.lisp"))
(load (pathname "meninlabfiles/constants.lisp"))
(load (pathname "meninlabfiles/classes.lisp"))
(load (pathname "meninlabfiles/methods.lisp"))
(load (pathname "meninlabfiles/commands.lisp"))
(load (pathname "meninlabfiles/functions.lisp"))
(load (pathname "zones/zones.lisp"))
(load-monsters-db)

(menu)
